POST https://visitor.6developer.com/visit
Content-Type: application/json

{
  "domain": "6developer.com",
  "timezone": "Asia/Seoul"
}

###

GET http://127.0.0.1:5000/visit?domain=6developer.com
Content-Type: application/json

{}

###
